### ISSUE TITLE
Missing function in W8.1 ?

### ISSUE THREAD

**Issue by Mecanik** [JustasMasiulis/lazy_importer#14] opened 2018-12-03 16:59 UTC
I stumbled on this, my app was crashing for no reason. Until I discovered that "StrFormatByteSizeW" was not loading with lazy impoter...

Function is part of Shlwapi.dll.

Any idea why ?

**Comment by JustasMasiulis** [comment] 2018-12-03 18:14
Could you provide some more information?
- Which function are you using?
- Does the safe version of the function return null or crash?

Possible reasons:
- It's a forwarded export and you don't have them enabled / using function that doesn't resolve them.
- The function actually doesn't exist in that windows version.
- There's a bug in my code.

**Comment by Mecanik** [comment] 2018-12-03 20:06
Well I am using StrFormatByteSizeW for my download using CURL, and it does work fine on Windows 10 x64, however when I tested on the latest Windows 8.1 x64 it was crashing.

I was using "LI_FIND_CACHED" for this, and for now I have removed it. ( I did not pull your latest lib yet, as you stated it's not stable ).

Function should be present in Shlwapi.dll since Windows 2000 Server.

Does this help ?

**Comment by JustasMasiulis** [comment] 2018-12-03 20:38
The new API is stable, although it hasn't yet been tested too thoroughly as haven't yet merged it into my main projects.

Concerning the problem I really have no idea why it wouldn't work on windows 8.1 but be fine on windows 10.

There could be multiple places where the issue occurs but I can't really test it as I have no windows 8.1 machines.

**Comment by Mecanik** [comment] 2018-12-03 20:41
I'm not sure how I could help, advise ?

**Comment by JustasMasiulis** [comment] 2018-12-03 21:00
Well assuming you have enabled forwarded exports resolving and have access to windows 8.1 system to test on it would be helpful to know whether you reach [the place where it actually finds the export](https://github.com/JustasMasiulis/lazy_importer/blob/bc128318f9aa87e17890883bb8cbfed93325f958/include/lazy_importer.hpp#L572)

if you do reach it try stepping trough and seeing what actually causes the crash.

For an export that is forwarded the `export.address(i)` should point to a C string. If you reach a point where it's unreadable/gibberish and still try to recurse deeper that is a problem. Not really sure what other hints I can provide.

If this doesn't help or you don't have a win 8.1 I could try getting myself a windows 8.1 VM, but that would take a bit of time (tomorrow at best if I have some time).

**Comment by Mecanik** [comment] 2018-12-18 17:02
I still did not get a chance to test and debug... I was trying today your new API, in a x64 application ( vs 2017 latest, windows 10 pro x64 latest, and the following is failing as well:

```
LI_FN(CreateDirectoryA).in(LI_MODULE("kernel32.dll").cached())
LI_FN(CreateFileA).in(LI_MODULE("kernel32.dll").cached())
LI_FN(SetFilePointer).in(LI_MODULE("kernel32.dll").cached())
```

Interesting because these functions are working in the "old" API that you made.

I would also like to mention that currently I am using this new API for 1 function "CloseHandle", and the application does not exit properly anymore :(

**Comment by JustasMasiulis** [comment] 2018-12-24 17:48
Sorry for the delay - I was taking a break from programming / my projects due to various other things taking place in my life.

On my machine the problem causing failures for your code snippet is the fact that the kernel32.dll is actually KERNEL32.DLL so defining LAZY_IMPORTER_CASE_INSENSITIVE fixes it.

Concerning the CloseHandle issue I'd need some more information.

**Comment by Mecanik** [comment] 2019-01-27 10:51
It seems like LAZY_IMPORTER_CASE_INSENSITIVE did fix the issue, however it now fails because I am using UNICODE in my project. 

Trying to see how I can resolve this.

Failing at:

1. https://i.imgur.com/ef5DM2U.png
2. https://i.imgur.com/0YVtzhW.png

**Comment by Mecanik** [comment] 2019-01-27 10:59
Actually that is a stupid mistake... You need to explicitly state with version of the function you want:

`CreateFilea/CreateFileW`

If you leave it just CreateFile macro, it will then fail.

**Comment by JustasMasiulis** [comment] 2019-01-27 11:05
Glad that the issue is fixed. I'll close this then.

**Closed by JustasMasiulis** 2019-01-27 11:05 UTC
Labels: investigating
